# Generated by Django 4.2 on 2023-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Link or Named Url'),
        ),
    ]
